$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: social-media-addiction-REGISTER-MODEL-52

display_name: Social media addiction

inputs:
  input_csv: 
    type: uri_file
    path: azureml:socialmedia_addiction_data:1
  train_percentage: 80
  e2e_flow_id: E2E-FLOW-3
  select_best_model_metric: mse

outputs:
  model: 
    mode: upload
  registration_details:
    mode: upload

settings:
  default_compute: azureml:default-machine-cli

jobs:
  split_data:
    type: command
    component: ../components/data/train_test_split.yaml
    inputs:
      input_csv: ${{parent.inputs.input_csv}}
      train_percentage: ${{parent.inputs.train_percentage}}
    outputs:
      output_train:
        type: uri_file
        path: azureml://datastores/workspaceblobstore/paths/social_media/train.csv
        mode: mount
      output_test:
        type: uri_file
        path: azureml://datastores/workspaceblobstore/paths/social_media/test.csv
        mode: mount
  # Train and Evaluate Random Forest Regressor
  train_model_random_forest_regressor:
    type: command
    component: ../components/train/train_model.yaml
    inputs:
      train_csv: 
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.split_data.outputs.output_train}}
      model_algorithm: random_forest
      e2e_flow_id: ${{parent.inputs.e2e_flow_id}}
      folds_config: 
        type: uri_file
        mode: ro_mount
        path: azureml:socialmedia_addiction_folds_config:1
      grid_search_config: 
        type: uri_file
        mode: ro_mount
        path: azureml:socialmedia_addiction_random_forest_regressor_grid_search_config:1
    outputs:
      mlflow_runid:
        type: uri_file
      model:
        type: uri_file

  evaluate_model_random_forest_regressor:
    type: command
    component: ../components/evaluate/evaluate_model.yaml
    inputs:
      test_csv:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.split_data.outputs.output_test}}
      mlflow_runid:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.train_model_random_forest_regressor.outputs.mlflow_runid}}
      model:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.train_model_random_forest_regressor.outputs.model}}
    outputs:
      mlflow_runid_of_model:
        type: uri_file
      output_model:
        type: uri_file

  # Train and Evaluate Support Vector Regressor
  train_model_support_vector_regressor:
    type: command
    component: ../components/train/train_model.yaml
    inputs:
      train_csv: 
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.split_data.outputs.output_train}}
      model_algorithm: support_vector
      e2e_flow_id: ${{parent.inputs.e2e_flow_id}}
      folds_config: 
        type: uri_file
        mode: ro_mount
        path: azureml:socialmedia_addiction_folds_config:1
      grid_search_config: 
        type: uri_file
        mode: ro_mount
        path: azureml:socialmedia_addiction_support_vector_regressor_grid_search_config:1
    outputs:
      mlflow_runid:
        type: uri_file
      model:
        type: uri_file

  evaluate_model_support_vector_regressor:
    type: command
    component: ../components/evaluate/evaluate_model.yaml
    inputs:
      test_csv:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.split_data.outputs.output_test}}
      mlflow_runid:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.train_model_support_vector_regressor.outputs.mlflow_runid}}
      model:
        type: uri_file
        mode: ro_mount
        path: ${{parent.jobs.train_model_support_vector_regressor.outputs.model}}
    outputs:
      mlflow_runid_of_model:
        type: uri_file
      output_model:
        type: uri_file

  # Select best model
  select_best_model:
    type: command
    component: ../components/evaluate/select_best_model.yaml
    inputs:
      e2e_flowid: ${{parent.inputs.e2e_flow_id}}
      select_metric: ${{parent.inputs.select_best_model_metric}}

      random_forest_model: ${{parent.jobs.evaluate_model_random_forest_regressor.outputs.output_model}}
      random_forest_runId: ${{parent.jobs.evaluate_model_random_forest_regressor.outputs.mlflow_runid_of_model}}
    
      support_vector_model: ${{parent.jobs.evaluate_model_support_vector_regressor.outputs.output_model}}
      support_vector_runId: ${{parent.jobs.evaluate_model_support_vector_regressor.outputs.mlflow_runid_of_model}}
    outputs:
      output_folder: ${{parent.outputs.model}}

  # Register model
  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    inputs:
      model_name: socialmedia_addication
      model_type: custom_model
      model_version: 1
      model_path: ${{parent.jobs.select_best_model.outputs.output_folder}}
    outputs:
      registration_details_folder: ${{ parent.outputs.registration_details }}