name: Socialmedia Addiction

on:
    push:
        branches: ["main"]
    workflow_dispatch:

env:
  GROUP: "HAC9909-MasterclassDeployingAISolutions"
  WORKSPACE: "vandaele-thijs-ml"
  LOCATION: "WestEurope"
  dockerregistry: ghcr.io/thijsvandaele8/mlops-animals-api

jobs:
    Azure-ML-setup:
        runs-on: self-hosted
        steps:
          - name: Check out repo
            uses: actions/checkout@v4

          - name: Azure Login
            uses: azure/login@v1
            with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Check if azure ml extension is installed
            run: az extension add --name ml

          - name: Azure configure defaults
            run: az configure --defaults group=${{ env.GROUP }} workspace=${{ env.WORKSPACE }} location=${{ env.LOCATION }}

          - name: Create compute
            run: ./scripts/azure/create_compute_if_not_exists.ps1 -ComputeName default-machine-cli

          - name: Ensure compute is running
            run: ./scripts/azure/ensure_compute_is_running.ps1 -ComputeName default-machine-cli

          - name: Create environments
            run: ./scripts/azure/create_environments.ps1

          - name: Create components
            run: ./scripts/azure/create_components.ps1
             
          - name: Create pipeline
            run: az ml job create --file ./aml/pipelines/multiple-ml-algorithms-pipeline.yaml --stream --set name=socialmedia-addiction-${{github.sha}}-${{github.run_id}}
