name: Socialmedia Addiction

on:
    push:
        branches: ["main"]
    workflow_dispatch:

env:
  GROUP: "HAC9909-MasterclassDeployingAISolutions"
  WORKSPACE: "vandaele-thijs-ml"
  LOCATION: "WestEurope"
  dockerregistry: ghcr.io/thijsvandaele8/mlops-socialmedia-addiction-api
  computename: default-machine-cli 
  no_azure_setup: 'false'

jobs:
    Azure-ML-setup:
        runs-on: self-hosted
        outputs:
          socialmedia_sourcecode_uri: ${{ steps.socialmedia_sourcecode.outputs.socialmedia_sourcecode_uri }}
        steps:
          - name: Check out repo
            uses: actions/checkout@v4

          - name: Azure Login
            uses: azure/login@v1
            with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Check if azure ml extension is installed
            run: az extension add --name ml

          - name: Azure configure defaults
            run: az configure --defaults group=${{ env.GROUP }} workspace=${{ env.WORKSPACE }} location=${{ env.LOCATION }}

          - name: socialmedia-addiction dataset -- Ensure data exists
            run: | 
                  ./scripts/azure/create_datafile_if_changed.ps1 `
                    -contentPath ./data/bronze/Students_Social_Media_Addiction.csv `
                    -dataYamlPath ./aml/data/datasets/socialmedia-addiction.yaml `
                    -dataName socialmedia_addiction_data

          - name: folds config -- Ensure data exists
            run: | 
                  ./scripts/azure/create_datafile_if_changed.ps1 `
                    -contentPath ./config/train/folds.json `
                    -dataYamlPath ./aml/data/configs/folds.yaml `
                    -dataName socialmedia_addiction_folds_config

          - name: random forest regressor grid search config -- Ensure data exists
            run: | 
                  ./scripts/azure/create_datafile_if_changed.ps1 `
                    -contentPath ./config/train/random_forest_regressor/grid_search.json `
                    -dataYamlPath ./aml/data/configs/random_forest_regressor.yaml `
                    -dataName socialmedia_addiction_random_forest_regressor_grid_search_config

          - name: support vector grid search config -- Ensure data exists
            run: | 
                  ./scripts/azure/create_datafile_if_changed.ps1 `
                    -contentPath ./config/train/support_vector_regressor/grid_search.json `
                    -dataYamlPath ./aml/data/configs/support_vector_regressor.yaml `
                    -dataName socialmedia_addiction_support_vector_regressor_grid_search_config

          - name: build and upload socialmedia python code
            id: socialmedia_sourcecode
            run: | 
                ./scripts/azure/build_and_upload_socialmedia_python_scripts.ps1 `
                    -workspaceName ${{ env.WORKSPACE }} -resourceGroup ${{ env.GROUP }} `
                    -wheelPath ./dist/socialmedia_mlops-0.1.2-py3-none-any.whl `
                    -contentPath ./src `
                    -dataYamlPath ./aml/data/code/socialmedia_sourcecode_wheel.yaml `
                    -dataName socialmedia_modeling_whl

          - name: Create environments
            if: ${{ env.no_azure_setup != 'true' }}
            run: ./scripts/azure/create_environments.ps1 -socialmedia_SourceCode_Uri '${{ steps.socialmedia_sourcecode.outputs.socialmedia_sourcecode_uri }}'

          - name: Create components
            if: ${{ env.no_azure_setup != 'true' }}
            run: ./scripts/azure/create_components.ps1

          - name: Create compute
            if: ${{ env.no_azure_setup != 'true' }}
            run: ./scripts/azure/create_compute_if_not_exists.ps1 -ComputeName ${{env.computename}}

          - name: Ensure compute is running
            if: ${{ env.no_azure_setup != 'true' }}
            run: ./scripts/azure/ensure_compute_is_running.ps1 -ComputeName ${{env.computename}}

          - name: Create pipeline
            if: ${{ env.no_azure_setup != 'true' }}
            run: az ml job create --file ./aml/pipelines/multiple-ml-algorithms-pipeline.yaml --stream --set name=socialmedia-addiction-${{ github.sha }}-${{ github.run_id }}

    download:
      if: true
      runs-on: self-hosted
      needs: Azure-ML-setup
      steps:
          - name: Azure Login
            uses: azure/login@v1
            with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Azure configure defaults
            run: az configure --defaults group=${{ env.GROUP }} workspace=${{ env.WORKSPACE }} location=${{ env.LOCATION }}

          - name: download model
            run: ./scripts/azure/download_model.ps1

    build-and-push:
      name: build and push to ghcr
      needs: download
      runs-on: self-hosted
      outputs:
        image_tag: ${{ steps.docker-meta-data.outputs.tags }}
      steps:
        - name: docker meta-data
          id: docker-meta-data
          uses: docker/metadata-action@v5.5.1
          with:
            images: |
              ${{ env.dockerregistry }}
            tags: |
              type=ref,event=branch
              type=sha
        
        - name: Docker -- Login to GHCR
          uses: docker/login-action@v3.2.0
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Build and push
          id: docker_build
          uses: docker/build-push-action@v5.3.0
          with:
            context: ./
            file: ./inference/Dockerfile
            push: true
            tags: ${{ steps.docker-meta-data.outputs.tags }}
  
    Deploy_to_k8s_with_helm:
      env:
        namespace: socialmedia-addiction-ns
      name: Deploy to k8s with helm 
      runs-on: self-hosted
      needs: build-and-push
      steps:
        - name: Helm upgrade or install
          run: ./scripts/azure/helm_install.ps1 -namespace ${{env.namespace}} -githubsha ${{ github.sha }} -dockerimage ${{ env.dockerregistry }}

